### ISSUE TITLE
env.fakeroot.sh can't handle some variables, causing invalid test failures

### ISSUE THREAD

**Issue by micahcowan** [dex4er/fakechroot#38]
Valid, or at least possible, environment variable names, are a superset of valid shell variable names. If the environment has a variable named, say, `FOO-BAR` (note the dash in the middle, which prevents it being a valid shell identifier), then most(?) shells (both dash and bash, at least) will not support removing them from the environment by means of the **unset** command. Which, of course, is what `env.fakeroot.sh` does.

A correct fix is probably honestly not worth the work it might cost. However, if you redirect stderr/stdout to /dev/null during just the unset loop, you can at least prevent shell complaints about the problem from being misinterpreted during test runs and causing falsely negative test results. Just be careful not to solve it in such a way that the unsets are evaluated in a subshell. :)

**Comment by micahcowan** [comment]
Potential solution/mitigation in pull request #39.

**Comment by dex4er** [comment]
Applied
