### ISSUE TITLE
LD_LIBRARY_PATH incorrect values with "fakechroot fakeroot chroot ... " after debootstrap --variant=fakechroot

### ISSUE THREAD

**Issue by dariemp** [dex4er/fakechroot#4]
I'm using fakechroot 2.16-1 from Debian and Ubuntu, on Ubuntu Precise 12.04 LTS.
After creating a system with fakechroot fakeroot debootstrap --variant=fakechroot ... , I've tried to build some packages inside it but they failed. Checking LD_LIBRARY_PATH i've found this:

$ fakechroot fakeroot chroot precise_amd64 /bin/bash

# echo $LD_LIBRARY_PATH
precise_amd64/usr/lib/libfakeroot:precise_amd64/usr/lib64/libfakeroot:precise_amd64/usr/lib32/libfakeroot:precise_amd64/usr/local/lib:precise_amd64/lib/x86_64-linux-gnu:precise_amd64/usr/lib/x86_64-linux-gnu:/usr/lib/libfakeroot:/usr/lib64/libfakeroot:/usr/lib32/libfakeroot:/home/dariemp/Work/Building/var/lib/nbs-slave/buildroots/precise_amd64/usr/lib:/home/dariemp/Work/Building/var/lib/nbs-slave/buildroots/precise_amd64/lib

Maybe i don't understand quite well how fakechroot works but i don't think it is correct that all those paths are escaping the chroot environment: all of them are relative to external directories. Shouldn't be all of them departing from the new root directory?

**Comment by ghost** [comment]
I just hit this issue myself, and was wondering whether this is at least documented anywhere. I have a setup which relies on `LD_LIBRARY_PATH` pointing to paths starting at the chroot dir, not the host's root.
