### ISSUE TITLE
libfakechroot.so linking fails when LTO

### ISSUE THREAD

**Issue by kloczek** [dex4er/fakechroot#56]
libtool: link: gcc -shared  -fPIC -DPIC  .libs/__fxstatat.o .libs/__fxstatat64.o .libs/__getcwd_chk.o .libs/__getwd_chk.o .libs/__lxstat.o .libs/__lxstat64.o .libs/__open.o .libs/__open64.o .libs/__open64_2.o .libs/__open_2.o .libs/__openat64_2.o .libs/__openat_2.o .libs/__opendir2.o .libs/__readlink_chk.o .libs/__readlinkat_chk.o .libs/__realpath_chk.o .libs/__statfs.o .libs/__xmknod.o .libs/__xmknodat.o .libs/__xstat.o .libs/__xstat64.o .libs/_xftw.o .libs/_xftw64.o .libs/access.o .libs/acct.o .libs/audit_log_acct_message.o .libs/bind.o .libs/bindtextdomain.o .libs/canonicalize_file_name.o .libs/chdir.o .libs/chmod.o .libs/chown.o .libs/chroot.o .libs/clearenv.o .libs/connect.o .libs/creat.o .libs/creat64.o .libs/dedotdot.o .libs/dl_iterate_phdr.o .libs/dladdr.o .libs/dlmopen.o .libs/dlopen.o .libs/eaccess.o .libs/euidaccess.o .libs/execl.o .libs/execle.o .libs/execlp.o .libs/execv.o .libs/execve.o .libs/execvp.o .libs/faccessat.o .libs/fchmodat.o .libs/fchownat.o .libs/fopen.o .libs/fopen64.o .libs/freopen.o .libs/freopen64.o .libs/fts.o .libs/fts64.o .libs/ftw.o .libs/ftw64.o .libs/futimesat.o .libs/get_current_dir_name.o .libs/getcwd.o .libs/getcwd_real.o .libs/getpeername.o .libs/getsockname.o .libs/getwd.o .libs/getxattr.o .libs/glob.o .libs/glob64.o .libs/glob_pattern_p.o .libs/inotify_add_watch.o .libs/lchmod.o .libs/lchown.o .libs/lckpwdf.o .libs/lgetxattr.o .libs/libfakechroot.o .libs/link.o .libs/linkat.o .libs/listxattr.o .libs/llistxattr.o .libs/lremovexattr.o .libs/lsetxattr.o .libs/lstat.o .libs/lstat64.o .libs/lutimes.o .libs/mkdir.o .libs/mkdirat.o .libs/mkdtemp.o .libs/mkfifo.o .libs/mkfifoat.o .libs/mknod.o .libs/mknodat.o .libs/mkostemp.o .libs/mkostemp64.o .libs/mkostemps.o .libs/mkostemps64.o .libs/mkstemp.o .libs/mkstemp64.o .libs/mkstemps.o .libs/mkstemps64.o .libs/mktemp.o .libs/open.o .libs/open64.o .libs/openat.o .libs/openat64.o .libs/opendir.o .libs/pathconf.o .libs/popen.o .libs/posix_spawn.o .libs/posix_spawnp.o .libs/rawmemchr.o .libs/readlink.o .libs/readlinkat.o .libs/realpath.o .libs/rel2abs.o .libs/rel2absat.o .libs/remove.o .libs/removexattr.o .libs/rename.o .libs/renameat.o .libs/revoke.o .libs/rmdir.o .libs/rpl_lstat.o .libs/scandir.o .libs/scandir64.o .libs/setenv.o .libs/setxattr.o .libs/stat.o .libs/stat64.o .libs/statfs.o .libs/statfs64.o .libs/statvfs.o .libs/statvfs64.o .libs/stpcpy.o .libs/strchrnul.o .libs/strlcpy.o .libs/symlink.o .libs/symlinkat.o .libs/system.o .libs/tempnam.o .libs/tmpnam.o .libs/truncate.o .libs/truncate64.o .libs/ulckpwdf.o .libs/unlink.o .libs/unlinkat.o .libs/utime.o .libs/utimensat.o .libs/utimes.o   -ldl -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -O2 -g -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -flto -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin   -Wl,-soname -Wl,libfakechroot.so -o .libs/libfakechroot.so
__lxstat64.h:40:5: warning: type of '__lxstat64_rel' does not match original declaration [-Wlto-type-mismatch]
 int __lxstat64_rel(int, const char *, struct stat64 *);
     ^
__lxstat64.c:53:11: note: '__lxstat64_rel' was previously declared here
 LOCAL int __lxstat64_rel(int ver, const char * filename, struct stat64 * buf)
           ^
__lxstat64.c:53:11: note: code may be misoptimized unless -fno-strict-aliasing is used
In function '__open64_alias':
lto1: fatal error: Cgraph edge statement index out of range

**Comment by marxin** [comment]
It's bug in GCC, I reported that with a reduced test-case:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88220

**Comment by dex4er** [comment]
It works with Debian buster so I'm closing this report

**Comment by kloczek** [comment]
This is not a bug in gcc.
Look carefully on declaration and definition on mentioned lines in warning.

**Comment by marxin** [comment]
> This is not a bug in gcc.

It is, we shouldn't crash on that code :)

**Comment by kloczek** [comment]
Issue is that this warning forces to not optimise using LTO exact part of the code if some types between declarations and places are not matching. All what needs to be done is remove such mismatch.
However to do this you need to know which variant is correct/right  :)

**Comment by kloczek** [comment]
Actually .. I must apologise.
After one more time have look on the code I found that you are right and I was wrong :/
And I just made the test using gcc 9 from  Fedora rawhide and there is no this issue anymore
