### ISSUE TITLE
block scoped variable life range violation

### ISSUE THREAD

**Issue by r-lar** [dex4er/fakechroot#62]
In src/libfakechroot.h there is
```c
   #define expand_chroot_path(path) 
    { 
        if (!fakechroot_localdir(path)) { 
            if ((path) != NULL) { 
                char fakechroot_abspath[FAKECHROOT_PATH_MAX]; 
                rel2abs((path), fakechroot_abspath); 
                (path) = fakechroot_abspath; 
                expand_chroot_rel_path(path); 
            } 
        } 
    }
```
The address of the block local scoped char array ``abspath`` is erroneously passed to the outer scoped ``path``. This can fail anytime and randomly, especially when enabling compiler optimizations.

There are more such pieces in the source code for example in bind.c
```c
        if (af_unix_path != NULL) {
            char tmp[FAKECHROOT_PATH_MAX];
            tmp[af_unix_path_max] = '\0';
            snprintf(tmp, af_unix_path_max, "%s/%s", af_unix_path, path);
            path = tmp;
        }
```
where the contents of ``tmp`` pointed to by ``path`` can evaporate anytime.

**Comment by dex4er** [comment]
Thanks for tip. That explains why fakechroot breaks with clang.

**Comment by r-lar** [comment]
Please reopen this issue because the mentioned commit fixes only very few manifestations of this problem.
Every single usage of the macros `expand_chroot_path` `expand_chroot_path_at` and `expand_chroot_rel_path` suffers from the same problem. Those are many. I think to fix this all these macros need an extra argument with a pointer to a temporary array, and such an array needs to be added to every invocation at the proper scope.
I tried that, the diffs are very lengthy. At least I'd restore the -O2 to -O0 to reduce probabilty of surprises.

**Comment by r-lar** [comment]
Attached is a rather unpolished series of commits which might do the job.

[scope-fix-1.tar.gz](https://github.com/dex4er/fakechroot/files/2932986/scope-fix-1.tar.gz)

**Comment by dex4er** [comment]
I already fixed it in commit dc302bb8f254edb288aa3e456b56058f3449cec5 so maybe we can keep this issue closed?

**Comment by r-lar** [comment]
Yes, I think this commit has fixed the issue, though it is of course difficult now to check for correct usage of those hidden buffers (whether the buffer is used twice within the same function for example)

Thanks,

**Comment by dex4er** [comment]
I agree this solution with macros is not pretty. Maybe I'll introduce additional macros that creates necessary variables, ie.:

```c
wrapper(creat, int, (const char * pathname, mode_t mode))
{
    expand_chroot_path_vars();
    debug("creat(\"%s\", 0%o)", pathname, mode);
    expand_chroot_path(pathname);
    return nextcall(creat)(pathname, mode);
}
```

**Comment by r-lar** [comment]
I don't think it would improve readability if the hidden variables would be hidden even more. And there are at least two of them and not always both will be used, causing warnings, needing attributes to shut off the warnings etc etc. It might be better to give those hidden variables a very special and outstanding name, for example "special_tmpbuf" or something like that. Still non obviously hiding the fact that something like
```c
  p1 = expand...(path1);
  p2 = expand...(path2);
  useof(p1 and p2);
```
will fail badly.
